title: Mi Portfolio
description: Este sera el portfolio de Ferran Beltran Sansano, espero que te guste:).
theme: Que haremos durante el curso

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
